/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ettprojekt;

import static ettprojekt.EttProjekt.idb;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author Christoffer
 */
public class bloggLayout extends javax.swing.JFrame {

    private inlaggFrame panel;

    private Validering val;
    private static String projekt;
    private static String utbildningProjekt;

    /**
     * Creates new form bloggLayout
     *
     *
     *
     */
    public bloggLayout() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        panel = new inlaggFrame();
        val = new Validering();

    }

    public String getProjektNamn() {

        return projekt;
    }

    public void setProjektNamn() {

        projekt = (String) projektBox.getSelectedItem();

    }

    public void setUtbildningNamn() {
        utbildningProjekt = (String) utbildningBox.getSelectedItem();
    }

    public String getUtbildningProjekt() {
        return utbildningProjekt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        projektBox = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillProjekt(projektBox);
        visaProjekt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        utbildningBox = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillUtbildningProjekt(utbildningBox);
        jLabel2 = new javax.swing.JLabel();
        visaUtbildningProjekt = new javax.swing.JButton();
        taBortProjekt = new javax.swing.JButton();
        nyttForskningProjekt = new javax.swing.JButton();
        nyUtbildning = new javax.swing.JButton();
        taBortUtbildning = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 450));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        visaProjekt.setText("Visa");
        visaProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaProjektActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Forskningsprojekt");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Utbildningsprojekt");

        visaUtbildningProjekt.setText("Visa");
        visaUtbildningProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visaUtbildningProjektActionPerformed(evt);
            }
        });

        taBortProjekt.setText("Ta bort projekt");
        taBortProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortProjektActionPerformed(evt);
            }
        });

        nyttForskningProjekt.setText("Nytt projekt");
        nyttForskningProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyttForskningProjektActionPerformed(evt);
            }
        });

        nyUtbildning.setText("Nytt projekt");
        nyUtbildning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyUtbildningActionPerformed(evt);
            }
        });

        taBortUtbildning.setText("Ta bort projekt");
        taBortUtbildning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortUtbildningActionPerformed(evt);
            }
        });

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(visaProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(projektBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nyttForskningProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taBortProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(visaUtbildningProjekt, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(utbildningBox, 0, 135, Short.MAX_VALUE)
                            .addComponent(nyUtbildning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(taBortUtbildning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projektBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utbildningBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visaProjekt)
                    .addComponent(visaUtbildningProjekt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nyttForskningProjekt)
                    .addComponent(nyUtbildning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taBortProjekt)
                    .addComponent(taBortUtbildning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/loggo_liten.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel4.setText("Projektsida");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("- Välj projekt att visa, skapa nytt projekt eller ta bort projekt");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/mus.png"))); // NOI18N
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visaProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaProjektActionPerformed
        EttProjekt.siffraVilken = 1;
        setProjektNamn();
        new projektBloggen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_visaProjektActionPerformed

    private void nyttForskningProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyttForskningProjektActionPerformed
        EttProjekt.siffraVilken = 1;
        new nyttProjekt().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nyttForskningProjektActionPerformed

    private void taBortProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortProjektActionPerformed
        try {

            if (val.isProjektAgare(projektBox)) {
                String projektNamn = (String) projektBox.getSelectedItem();
                String id = "SELECT PROJEKT_ID FROM PROJEKT WHERE PROJEKTNAMN = '" + projektNamn + "'";
                String projektId = idb.fetchSingle(id);
                String fraga2 = "DELETE FROM PROJEKT WHERE PROJEKTNAMN = '" + projektNamn + "'";
                System.out.println(fraga2);
                String fraga1 = "DELETE FROM PROJEKT_INLAGG WHERE PROJEKT_ID = '" + projektId + "'";
                System.out.println(fraga1);
                String fraga3 = "DELETE FROM DELTAR_I_PROJEKT WHERE PROJEKT_ID = '" + projektId + "'";

                idb.delete(fraga1);
                idb.delete(fraga3);
                idb.delete(fraga2);
                ComboBox.cboxLaggTillProjekt(projektBox);
                JOptionPane.showMessageDialog(null, "Projekt har tagits bort");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }//GEN-LAST:event_taBortProjektActionPerformed

    private void nyUtbildningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyUtbildningActionPerformed
        EttProjekt.siffraVilken = 2;
        new nyttProjekt().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nyUtbildningActionPerformed

    private void taBortUtbildningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortUtbildningActionPerformed
        try {
            if (val.isProjektAgare(utbildningBox)) {
                String projektNamn = (String) utbildningBox.getSelectedItem();
                String id = "SELECT UTBILDNINGS_ID FROM UTBILDNING WHERE UTBILDNINGSNAMN = '" + projektNamn + "'";
                String projektId = idb.fetchSingle(id);
                String fraga2 = "DELETE FROM UTBILDNING WHERE UTBILDNINGSNAMN = '" + projektNamn + "'";
                System.out.println(fraga2);
                String fraga1 = "DELETE FROM UTBILDNING_INLAGG WHERE UTBILDNINGS_ID = '" + projektId + "'";
                System.out.println(fraga1);
                String fraga3 = "DELETE FROM DELTAR_I_UTBILDNING WHERE UTBILDNINGS_ID = '" + projektId + "'";

                idb.delete(fraga3);
                idb.delete(fraga1);
                idb.delete(fraga2);
                ComboBox.cboxLaggTillProjekt(utbildningBox);
                JOptionPane.showMessageDialog(null, "Projekt har tagits bort");
            }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }
    }//GEN-LAST:event_taBortUtbildningActionPerformed

    private void visaUtbildningProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visaUtbildningProjektActionPerformed
        EttProjekt.siffraVilken = 2;
        setUtbildningNamn();
        new UtbildningProjektFlode().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_visaUtbildningProjektActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton nyUtbildning;
    private javax.swing.JButton nyttForskningProjekt;
    private javax.swing.JComboBox<String> projektBox;
    private javax.swing.JButton taBortProjekt;
    private javax.swing.JButton taBortUtbildning;
    private javax.swing.JComboBox<String> utbildningBox;
    private javax.swing.JButton visaProjekt;
    private javax.swing.JButton visaUtbildningProjekt;
    // End of variables declaration//GEN-END:variables
}
