package ettprojekt;

import javax.swing.JOptionPane;
import oru.inf.InfException;
import static ettprojekt.EttProjekt.idb;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author idabe
 */
public class HanteraAnvandare extends javax.swing.JFrame {

    /**
     * Creates new form BjudInAnvandare
     */
    public HanteraAnvandare() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnBjud = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        cboxMail = new javax.swing.JComboBox<>();
        ComboBox.cboxLaggTillEmail(cboxMail);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        btnBjud.setText("Bjud in användare");
        btnBjud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBjudActionPerformed(evt);
            }
        });

        btnTaBort.setText("Ta bort användare");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnBjud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnTaBort)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBjud)
                    .addComponent(btnTaBort))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jLabel1.setText("Användarens email:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxMail, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBjudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBjudActionPerformed
        try {

            bloggLayout layout = new bloggLayout();

            String email = txtMail.getText();
            String fraga1 = ("SELECT USER_ID FROM USERS WHERE EMAIL = '" + email + "';");
            System.out.println(fraga1);
            String userId = idb.fetchSingle(fraga1);
            
            if(EttProjekt.siffraVilken ==1 ){
            String projektNamn = layout.getProjektNamn();
            String fraga2 = ("SELECT PROJEKT_ID FROM PROJEKT WHERE PROJEKTNAMN = '" + projektNamn + "';");
            System.out.println(fraga2);
            String projektId = idb.fetchSingle(fraga2);

            String fraga = ("INSERT INTO DELTAR_I_PROJEKT VALUES ('" + projektId + "', '" + userId + "');");
            System.out.println(fraga);
            idb.insert("INSERT INTO DELTAR_I_PROJEKT VALUES ('" + projektId + "', '" + userId + "');");
            } 
            else if(EttProjekt.siffraVilken == 2){
            System.out.println(EttProjekt.siffraVilken);
            String utbildningNamn = layout.getUtbildningProjekt();
            String fraga3 = ("SELECT UTBILDNINGS_ID FROM UTBILDNING WHERE UTBILDNINGSNAMN = '" + utbildningNamn + "';");
            
            String utbildningId = idb.fetchSingle(fraga3);
            System.out.println(utbildningId);
            String fraga = ("INSERT INTO DELTAR_I_UTBILDNING VALUES ('" + utbildningId + "', '" + userId + "');");
            System.out.println(fraga);
            idb.insert("INSERT INTO DELTAR_I_UTBILDNING VALUES ('" + utbildningId + "', '" + userId + "');");
            }
            txtMail.setText(null);

            JOptionPane.showMessageDialog(null, email + " är tillagd");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt felmeddelande" + e.getMessage());

        }
    }//GEN-LAST:event_btnBjudActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        try {

            String email = (String) cboxMail.getSelectedItem();

            String fraga1 = ("SELECT USER_ID FROM USERS WHERE EMAIL = '" + email + "';");
            System.out.println(fraga1);
            String userId = idb.fetchSingle(fraga1);

            String fraga = ("DELETE FROM DELTAR_I_PROJEKT WHERE USER_ID = (" + userId + ");");
            System.out.println(fraga);
            idb.delete(fraga);

            JOptionPane.showMessageDialog(null, email + " är borttagen");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("Internt felmeddelande" + e.getMessage());

        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBjud;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> cboxMail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMail;
    // End of variables declaration//GEN-END:variables
}
