/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ettprojekt;

import static ettprojekt.EttProjekt.idb;
import static ettprojekt.EttProjekt.userDir;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author mira
 */
public class Profil extends javax.swing.JFrame {

    public static InfDB idb;
    String filename = null;
    byte[] person_image = null;
    int id;

    /**
     * Creates new form profil
     */
    public Profil() {
        initComponents();

        userDir = System.getProperty("user.dir"); //Hämtar vart programmet körs ifrån
        userDir += "/lib/DATABASE.FDB"; //Pekar på vart databasen ligger lagrad
        try {
            //Importerar databasen
            idb = new InfDB(EttProjekt.userDir);
            System.out.println(userDir);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("fel:" + e);
        }
        setinfo();

        User u = User.getInstance();
        id = u.getID();

    }

    public void setinfo() {
        try {

            User u = User.getInstance();
            int id = u.getID();
            System.out.println(id);

            String hamtafnamn = "SELECT FIRST_NAME from users where user_id =" + id + ";";
            String fnamn = idb.fetchSingle(hamtafnamn);

            String hamtaenamn = "SELECT LAST_NAME from users where user_id = " + id + ";";
            String enamn = idb.fetchSingle(hamtaenamn);

            String hamtalosen = "SELECT LOSENORD from users where user_id =" + id + ";";
            System.out.println(hamtalosen);

            String hamtatel = "SELECT TELEFON from users where user_id =" + id + ";";
            System.out.println(hamtatel);

            String hamtabild = "SELECT BILDER from users where user_id =" + id + ";";
            System.out.println(hamtabild);

            String bild = idb.fetchSingle(hamtabild);
            System.out.println(bild + ".");
            try {
                bild = bild.replaceAll("\\s+", "");
            } catch (NullPointerException i) {
            }
            System.out.println(bild + ".");

            String losen = idb.fetchSingle(hamtalosen);
            System.out.println(losen);

            String tel = idb.fetchSingle(hamtatel);
            System.out.println(tel);

            String hamtamejl = "SELECT EMAIL from users where user_id =" + id + ";";
            String mejlen = idb.fetchSingle(hamtamejl);

            lbfnamn.setText(fnamn);
            lbenamn.setText(enamn);
            txtlosen.setText(losen);
            txtmejl.setText(mejlen);
            txttel.setText(tel);
            //String test = ("/Users/mira/NetBeansProjects/ettProjekt/ettProjekt/files/2019-02-08 12.54.06.108-asplund.jpg");
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(bild).getImage().getScaledInstance(lblbild.getWidth(), lblbild.getHeight(), Image.SCALE_SMOOTH));
            lblbild.setIcon(imageIcon);

        } catch (InfException e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbfnamn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbenamn = new javax.swing.JLabel();
        lbmejl = new javax.swing.JLabel();
        lblosen = new javax.swing.JLabel();
        txtmejl = new javax.swing.JTextField();
        txtlosen = new javax.swing.JTextField();
        btnbild = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblbild = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel1.setText("Förnamn");

        lbfnamn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        lbfnamn.setText("namn");

        jLabel3.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        jLabel3.setText("Efternamn");

        lbenamn.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        lbenamn.setText("namn");

        lbmejl.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        lbmejl.setText("Mejl");

        lblosen.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        lblosen.setText("Lösenord");

        txtmejl.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N

        txtlosen.setFont(new java.awt.Font("Shree Devanagari 714", 0, 13)); // NOI18N

        btnbild.setText("Byt bild");
        btnbild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbildActionPerformed(evt);
            }
        });

        btnupdate.setText("Uppdatera");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 2, 36)); // NOI18N
        jLabel2.setText("Profil");

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setForeground(new java.awt.Color(0, 51, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        lblbild.setText("bild");

        lbltel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N
        lbltel.setText("Tel");

        txttel.setFont(new java.awt.Font("Shree Devanagari 714", 0, 14)); // NOI18N

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/loggo_liten.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(86, 86, 86)
                            .addComponent(lbenamn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(95, 95, 95)
                            .addComponent(lbfnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbmejl)
                            .addComponent(lblosen)
                            .addComponent(lbltel))
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmejl, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(txtlosen)
                            .addComponent(txttel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbild)
                    .addComponent(lblbild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jButton1)
                .addGap(121, 121, 121)
                .addComponent(btnupdate)
                .addGap(122, 450, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel5)
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbfnamn))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbenamn))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltel)
                            .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbmejl)
                            .addComponent(txtmejl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblbild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblosen)
                    .addComponent(txtlosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbild))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(jButton1))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        try {
            User u = User.getInstance();
            int id = u.getID();
            System.out.println(id);

            String losenord = txtlosen.getText();
            System.out.println(losenord);
            String mejl = txtmejl.getText();
            String tel = txttel.getText();

            String sql = "update users set LOSENORD ='" + losenord + "' ,EMAIL= '" + mejl + "',TELEFON= '" + tel + "' where  USER_ID = '" + id + "';";
            System.out.println(sql);
            idb.update(sql);
            try {
                try {
                    String output = filePicker.fileSaverProfil(filename, id);
                    File outputFile = new File(output);
                    System.out.println(output);
                    File inputFile = new File(filename);
                    fileSave.copyFileUsingStream(inputFile, outputFile);
                    String fraga = ("UPDATE USERS SET BILDER = '" + output + "' WHERE USER_ID = '" + id + "';");
                    System.out.println(fraga);
                    idb.update(fraga);
                } catch (IOException i) {
                }
            } catch (InfException e) {
            }

            JOptionPane.showMessageDialog(null, "Användare har uppdaterats!");

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage());
        }


    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnbildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbildActionPerformed
        String file = filePicker.filePicker();
        System.out.println(file);
        filename = file;
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lblbild.getWidth(), lblbild.getHeight(), Image.SCALE_SMOOTH));
        lblbild.setIcon(imageIcon);
//        try{
//            File image = new File(filename);
//            FileInputStream fis = new FileInputStream(image);
//            ByteArrayOutputStream bos = new ByteArrayOutputStream();
//            byte[] buf = new byte[1024];
//            for(int readNum; (readNum = fis.read(buf)) !=-1;){
//                bos.write(buf,0,readNum);
//            }
//             person_image=bos.toByteArray();
//           }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null,e);
//            
//        }
    }//GEN-LAST:event_btnbildActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbild;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbenamn;
    private javax.swing.JLabel lbfnamn;
    private javax.swing.JLabel lblbild;
    private javax.swing.JLabel lblosen;
    private javax.swing.JLabel lbltel;
    private javax.swing.JLabel lbmejl;
    private javax.swing.JTextField txtlosen;
    private javax.swing.JTextField txtmejl;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

}
