package ettprojekt;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import static ettprojekt.EttProjekt.userDir;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import org.apache.commons.io.FilenameUtils;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author mira
 */
public class skapaanvandare extends javax.swing.JFrame {

    /**
     * Creates new form skapaanvandare
     */
    public static InfDB idb;

    public skapaanvandare() {
        initComponents();
        userDir = System.getProperty("user.dir"); //Hämtar vart programmet körs ifrån
        userDir += "/lib/DATABASE.FDB"; //Pekar på vart databasen ligger lagrad
        try {
            //Importerar databasen
            idb = new InfDB(EttProjekt.userDir);
            System.out.println(userDir);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
            System.out.println("fel:" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtFornamn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmejl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEfternamn = new javax.swing.JTextField();
        btnGenereraLosenord = new javax.swing.JButton();
        txtlosen = new javax.swing.JTextField();
        lblBild = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        jLabel3.setText("Förnamn");

        jLabel4.setText("Mejl");

        jLabel5.setText("Telefon nr");

        jButton1.setText("Skapa användare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Lösenord");

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Användare", "Admin" }));
        cbstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstatusActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/add-user-male.png"))); // NOI18N

        jLabel2.setText("Efternamn");

        btnGenereraLosenord.setText("Generera");
        btnGenereraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenereraLosenordActionPerformed(evt);
            }
        });

        txtlosen.setEditable(false);

        lblBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/gender-neutral-user-filled.png"))); // NOI18N

        jLabel11.setText("Profilbild");

        jButton2.setText("Avbryt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(txttel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(txtmejl)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(txtFornamn)
                                .addComponent(txtEfternamn)))))
                .addGap(146, 146, 146)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txtlosen, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(btnGenereraLosenord))
                        .addComponent(jLabel7)
                        .addComponent(jLabel11)
                        .addComponent(lblBild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlosen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenereraLosenord))
                        .addGap(37, 37, 37)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmejl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBild, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 2, 24)); // NOI18N
        jLabel1.setText("Skapa Användare");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bilder/loggo_liten.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //if(Validering.textFaltHarVarde(txtFornamn) && (Validering.textFaltHarVarde(txtEfternamn))
        if (Validering.isString(txtFornamn)) {

            if (Validering.isString(txtEfternamn)) {

                if (Validering.isHeltal(txttel)) {
                    if (Validering.isEmailFormatCorrect(txtmejl)) {

                        try {

                            String fornamn = txtFornamn.getText();
                            String efternamn = txtEfternamn.getText();
                            String mejl = txtmejl.getText();
                            String tel = txttel.getText();
                            String ID = idb.getAutoIncrement("USERS", "USER_ID");
                            System.out.println(ID);
                            String losen = txtlosen.getText();
                            String admin = cbstatus.getSelectedItem().toString();
                            String bild = System.getProperty("user.dir") + "/src/bilder/gender-neutral-user-filled.png";

                            String fraga = "SELECT USER_ID from USERS where USER_ID=" + ID;
                            String fraga1 = "INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, BILDER, TELEFON, TYPER, LOSENORD, USER_ID) VALUES('" + fornamn + "', '" + efternamn + "', '" + mejl + "','" + bild + "', '" + tel + "','ADMIN','" + losen + "', '" + ID + "');";
                            String fraga2 = "INSERT INTO USERS(FIRST_NAME, LAST_NAME, EMAIL, BILDER, TELEFON, TYPER, LOSENORD, USER_ID) VALUES('" + fornamn + "', '" + efternamn + "', '" + mejl + "','" + bild + "','" + tel + "','USER','" + losen + "', '" + ID + "');";

                            String svar = idb.fetchSingle(fraga);

                            if (ID.equals(svar)) {
                                JOptionPane.showMessageDialog(null, "användare finns redan i systemet");
                            } else {
                                if (admin.equals("Admin")) {
                                    idb.insert(fraga1);

                                } else {
                                    idb.insert(fraga2);

                                }
                                JOptionPane.showMessageDialog(null, "Ny användare tillagd");
                                //Efter att användaren är tillagd rensas fälten så de blir tomma
                                txtFornamn.setText("");
                                txtEfternamn.setText("");
                                txtmejl.setText("");
                                txttel.setText("");
                                txtlosen.setText("");
                            }

                        } catch (InfException e) {
                            JOptionPane.showMessageDialog(null, "Något gick fel!");
                            System.out.println("Internt felmeddelande" + e.getMessage());
                        }

                    }
                }
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstatusActionPerformed

        String admin = cbstatus.getSelectedItem().toString();
        System.out.println(admin);

    }//GEN-LAST:event_cbstatusActionPerformed

    private void btnGenereraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenereraLosenordActionPerformed
        //Den här metoden slumpar ett lösenord till en nyanvändare, detta ska sedan användaren själv byta 
        //Kravet på lösenord är att det ska vara åtta tecken varav minst en ska vara en siffra
        //Det slumpas alltså ut en siffra mellan 1-9
        //Sedan slumpas det 7 bokstäver
        //Dessa sätts ihop till en string som blir det genererade lösenordet

        String nummer = "0123456789";

        Random rnd = new Random();

        StringBuilder sb = new StringBuilder(1);

        for (int i = 0; i < 1; i++) {
            sb.append(nummer.charAt(rnd.nextInt(nummer.length())));
        }

        String bokstaver = "abcdefghijklmnopqrstuvwxyz";
        String storbokstav = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String tecken = "[!@#$%&*()_+=|<>?{}\\[\\]~-]";

        StringBuilder sbbb = new StringBuilder(1);
        for (int i = 0; i < 1; i++) {
            sbbb.append(storbokstav.charAt(rnd.nextInt(storbokstav.length())));
        }
        StringBuilder sbbbb = new StringBuilder(1);
        for (int i = 0; i < 1; i++){
            sbbb.append(tecken.charAt(rnd.nextInt(tecken.length())));
        }
        
        Random rand = new Random();

        StringBuilder sbb = new StringBuilder(6);

        for (int i = 0; i < 6; i++) {
            sbb.append(bokstaver.charAt(rand.nextInt(bokstaver.length())));
        }

        String random1 = sb.toString();
        String random2 = sbb.toString();
        String random3 = sbbb.toString();
        String random4 = sbbbb.toString();

        String random;
        random = random3 + random2 + random1 + random4;

        txtlosen.setText(random);
    }//GEN-LAST:event_btnGenereraLosenordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenereraLosenord;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBild;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtlosen;
    private javax.swing.JTextField txtmejl;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables

}
