/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ettprojekt;

import static ettprojekt.EttProjekt.idb;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author EmelieD
 */
public class UtbildningProjektFlode extends javax.swing.JFrame {
    private Validering val;

    /**
     * Creates new form UtbildningProjektFlode
     */
    public UtbildningProjektFlode() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        bloggInlaggen();
        val = new Validering();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelen = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meny = new javax.swing.JMenu();
        nyttInlagg = new javax.swing.JMenuItem();
        hanteraAnvandare = new javax.swing.JMenuItem();
        tillbaka = new javax.swing.JMenu();
        tillbakaUtbildning = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Utbildningsprojekt");

        javax.swing.GroupLayout panelenLayout = new javax.swing.GroupLayout(panelen);
        panelen.setLayout(panelenLayout);
        panelenLayout.setHorizontalGroup(
            panelenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelenLayout.setVerticalGroup(
            panelenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelen);

        meny.setText("Meny");

        nyttInlagg.setText("Nytt inlägg");
        nyttInlagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyttInlaggActionPerformed(evt);
            }
        });
        meny.add(nyttInlagg);

        hanteraAnvandare.setText("Hantera användare");
        hanteraAnvandare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hanteraAnvandareActionPerformed(evt);
            }
        });
        meny.add(hanteraAnvandare);

        jMenuBar1.add(meny);

        tillbaka.setText("Tillbaka");

        tillbakaUtbildning.setText("Tillbaka");
        tillbakaUtbildning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tillbakaUtbildningActionPerformed(evt);
            }
        });
        tillbaka.add(tillbakaUtbildning);

        jMenuBar1.add(tillbaka);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nyttInlaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyttInlaggActionPerformed
     bloggLayout layout = new bloggLayout();
     String projektNamn = layout.getUtbildningProjekt();
     if(val.isMedIUtbildningProjekt(projektNamn)){
     new nyttInlagg().setVisible(true);
     this.dispose();
     }
    }//GEN-LAST:event_nyttInlaggActionPerformed

    private void hanteraAnvandareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hanteraAnvandareActionPerformed
     bloggLayout l = new bloggLayout();    
     String projektNamn = l.getUtbildningProjekt();
     if(val.isUtbildningtAgareString(projektNamn)){
     new HanteraAnvandare().setVisible(true);
     this.dispose();
     }
    }//GEN-LAST:event_hanteraAnvandareActionPerformed

    private void tillbakaUtbildningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tillbakaUtbildningActionPerformed
         new bloggLayout().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_tillbakaUtbildningActionPerformed
    
    private void bloggInlaggen(){
         try {
            bloggLayout layout = new bloggLayout();
            String projektNamn = layout.getUtbildningProjekt();
            
            String fraga1 = "SELECT UTBILDNINGS_ID FROM UTBILDNING WHERE UTBILDNINGSNAMN = '" + projektNamn + "'";
            String projektId = idb.fetchSingle(fraga1);
            int projektIdInt = Integer.parseInt(projektId);
            String fraga2 = "SELECT INLAGG_ID FROM UTBILDNING_INLAGG WHERE UTBILDNINGS_ID = " + projektIdInt + ";";
            ArrayList<String> inlaggLista = idb.fetchColumn(fraga2);
          
            if (inlaggLista == null) {
                return;

            }
            Collections.reverse(inlaggLista);
            int antalInlagg = inlaggLista.size();
            String fragan = "SELECT TEXT FROM INLAGG JOIN UTBILDNING_INLAGG ON INLAGG.INLAGG_ID = UTBILDNING_INLAGG.INLAGG_ID WHERE UTBILDNINGS_ID = " + projektIdInt + ";";
            ArrayList<String> texter = idb.fetchColumn(fragan);
            Collections.reverse(texter);

            fragan = "SELECT TITEL FROM INLAGG JOIN UTBILDNING_INLAGG ON INLAGG.INLAGG_ID = UTBILDNING_INLAGG.INLAGG_ID WHERE UTBILDNINGS_ID = " + projektIdInt + ";";
            ArrayList<String> titlar = idb.fetchColumn(fragan);
            Collections.reverse(titlar);

            for (int j = 0; j < antalInlagg; j++) {
                inlaggFrame panel = new inlaggFrame();
                String id = inlaggLista.get(j);
                panelen.setLayout(new BoxLayout(panelen, BoxLayout.PAGE_AXIS));
                panelen.add(Box.createRigidArea(new Dimension(0, 20)));
                panelen.add(panel);
                panelen.setVisible(true);
                String allaTexter = texter.get(j);
                String allaTitlar = titlar.get(j);
                panel.setText(allaTexter);
                panel.setTitel(allaTitlar);
                panel.setID(id);
                System.out.println(id);
                panel.setUtbildningBloggen(this);
                panel.setEditable();
                panel.utbildningAgare();

                try {
                    String anvandare = "SELECT USER_ID FROM SKAPA_INLAGG WHERE INLAGG_ID = '" + id + "'";
                    String anvandarId = idb.fetchSingle(anvandare);
                    String fornamn = "SELECT FIRST_NAME FROM USERS WHERE USER_ID = '" + anvandarId + "'";
                    String fornamnet = idb.fetchSingle(fornamn);
                    String efternamn = "SELECT LAST_NAME FROM USERS WHERE USER_ID = '" + anvandarId + "'";
                    String efternamnet = idb.fetchSingle(efternamn);
                    String helaNamnet = fornamnet + " " + efternamnet;
                    panel.setSkapare(helaNamnet);
                    panel.inlaggAgare();
                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Användare fel");
                }

            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }

    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem hanteraAnvandare;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu meny;
    private javax.swing.JMenuItem nyttInlagg;
    private javax.swing.JPanel panelen;
    private javax.swing.JMenu tillbaka;
    private javax.swing.JMenuItem tillbakaUtbildning;
    // End of variables declaration//GEN-END:variables
}
